### ISSUE TITLE
SameParty should use/require cookie prefixes

### ISSUE THREAD

**Issue by dwaite** [cfredric/sameparty#3]
The same sort of cross-site state injection that can be done with Secure and Host cookie parameters could be done with SameParty. 

I recommend at a minimum that a cookie prefix (__SameParty-) by instituted to protect against this, and that we consider requiring prefixing as SameParty does not have a legacy compatibility issue.

**Comment by cfredric** [comment]
As I understand it, the `__Secure-` and `__Host-` prefixes give cookies confidentiality (by requiring the `Secure` attribute) and integrity (by preventing those cookies from being set by an attacker over HTTP).

I imagine that a `__SameParty-` prefix would let a server know that a given cookie was set with the `SameParty` attribute. However, I don't think a new prefix is necessary to achieve that. Instead, a server could use the existing `__Secure-` or `__Host-` prefix to guarantee cookie integrity. Such a cookie would be set with `SameParty` if and only if the server set the cookie with `SameParty`. So, if the server wants to ensure a cookie is set with the `SameParty` attribute, it needs only to use one of the existing prefixes in conjunction with the `SameParty` attribute.

I'll tentatively close this issue, but let me know if I've misunderstood.

I'll also note that `SameParty` is being proposed not as a _security_ boundary, but as a _privacy_ boundary. That is, existing security best-practices still apply.

**Comment by dwaite** [comment]
> I'll also note that SameParty is being proposed not as a security boundary, but as a privacy boundary. That is, existing security best-practices still apply.

Ahh, that is something I didn't quite understand from the explainer - this is not defining a method of browser sharing of state, but rather a way for content operating in (what is today) a third party context to be able to access state.

From the example given in the introduction - if you allowed shared state between a main origin and a user-generated content origin, you would absolutely need to define an explicit grouping of that state to prevent user-generated content from attempting to manipulate the main origin via injecting state. But this is about allowing one origin to access its own state when being shown in a context where it would normally be considered third party (without first party sets and the SameParty attribute)
